spring:
    jpa:
        database: mysql         
    datasource:
        url: jdbc:mysql://aspire-1705.aspiresys.com:3306/ingenico?useSSL=false
        username: mt
        password: mt
        driver-class-name: com.mysql.jdbc.Driver
        tomcat:
           test-while-idle: true
           test-on-borrow: true
           test-on-return: false
           validation-query: SELECT 1 FROM DUAL
           validation-queryTimeout: 30
           validation-interval: 30000
           max-active: 50
           min-idle: 5
           max-idle: 20
           max-wait: 10000
           initial-size: 5
           remove-abandoned-timeout: 600
           remove-abandoned: false
           time-between-eviction-runs-millis: 30000
           min-evictable-idle-time-millis: 30000
           url: ${spring.datasource.url}
           username: ${spring.datasource.username}
           password: ${spring.datasource.password}
           driver-class-name: ${spring.datasource.driver-class-name}

logging:
  file: /var/logs/transferService.log
  level:
    com:
      DEBUG

server:
  port: 8093
  servlet:
    context-path: /ingenico

      